schema_path: https://raw.githubusercontent.com/xafs-db/xafs-schema/main/draft/20230127/xafs-schema.json
#schema_path: https://raw.githubusercontent.com/xafs-db/xafs-schema/main/draft/20230127/xafs-schema-strict.json
#schema_path: ./draft/20230127/xafs-schema.json
#schema_path: ./draft/20230127/xafs-schema-strict.json